Feature/#13/swagger option
haru-speak/server pull request #16
Opened 2023-01-19 14:59 UTC by leeys1218

### ❗️ 이슈번호 

Closes #13 

### 📝 구현 내용

![image](https://user-images.githubusercontent.com/95534831/213473275-e6b2b369-6a15-4b7b-8159-daa49b51b6a6.png)

이런식으로 각 필드에 타입과 설명, NULL 허용 여부 등을 작성했습니다. 

지금 설명과 NULL 허용 여부가 description 속성 값에 한번에 들어가는데, 
nullable = false 같은 속성이 있긴 했지만 스웨거 ui 상으로 표시가 되지 않아 묶어서 표시했습니다.

각 api의 request, response에서 schema를 눌러 확인할 수 있습니다.
![image](https://user-images.githubusercontent.com/95534831/213475373-3d29fa0d-7536-45a4-ac4a-d217683d0f52.png)
![image](https://user-images.githubusercontent.com/95534831/213476014-10bfcc09-6d50-41f8-98c7-a7268a728238.png)

2023-01-19 17:27 UTC, nathan29849 commented
제목이 내용을 쉽게 알 수 있도록 바뀌면 좋을 것 같아요!
그리고 리뷰어는 서버 파트 3명(본인 제외)을 모두 지정해주세요!
또한 Assignee에는 본인을 지정해주세요!

2023-01-19 18:02 UTC, nathan29849 requested changes

2023-01-19 18:03 UTC, nathan29849 commented
일단 수정사항이 조금 있는 것같아 Request Changes를 걸어두었습니다!
리뷰와 코멘트를 확인하시고 수정을 하신 뒤에 다시 request를 눌러주세요! (주의! 머지 누르란 말이 아닙니다!!)

2023-01-20 00:54 UTC, leeys1218 commented
수정 사항은 다 적용하여 Re request 했습니다!

말씀하신 내용 기억해서 다음 PR때는 꼼꼼히 확인하겠습니다. 감사합니다!

2023-01-20 01:01 UTC, nathan29849 commented
아 제가 첫 댓글에 잘못 단게 있었네요..!

이슈 제목만 보고도 이슈 내용을 쉽게 알 수 있도록 수정해주시면 좋을 것 같습니다!!

2023-01-20 01:51 UTC, leeys1218 commented on be/src/main/java/com/example/be/core/application/dto/request/SpeakingLogModifyRequest.java
> +	@Schema(type = "String", description = "제목, NOT NULL")
수정 완료!

아직 뚜렷하게 의도가 구분되는 api는 modify 밖에 없는 것 같아서 
SpeakingLogModifyRequest 부분만 수정했습니다.

2023-01-20 01:51 UTC, leeys1218 commented on be/src/main/java/com/example/be/core/application/dto/request/SpeakingLogModifyRequest.java
> +	@Schema(type = "String", description = "음성 녹음 URL, NOT NULL")
수정 완료!

2023-01-20 01:52 UTC, leeys1218 commented on be/src/main/java/com/example/be/core/application/dto/request/SpeakingLogConditionRequest.java
> +	@Schema(type = "String", description = "생년월일, NOT NULL", example = "YYYYMMDD")
수정 완료!

2023-01-20 01:52 UTC, leeys1218 commented on be/src/main/java/com/example/be/core/web/SpeakingLogController.java
> +import io.swagger.v3.oas.annotations.tags.Tag;
숙지하겠습니다

2023-01-20 02:07 UTC, nathan29849 approved these changes

2023-01-20 02:10 UTC, leeys1218 commented on be/src/main/java/com/example/be/core/application/dto/response/SpeakingLogsResponse.java
> +	@Schema(enumAsRef = true, description = "스피킹 로그 조회 타입, NOT NULL")
Swagger 어노테이션이 코드에서 enum 타입을 추적해서 그에 대한 ui가 나오게 하는 것 같아요.
![image](https://user-images.githubusercontent.com/95534831/213603131-777fee0d-50f3-4846-8bbe-05bb2e2fdef2.png)

2023-01-20 02:12 UTC, nathan29849 commented on be/src/main/java/com/example/be/core/application/dto/response/SpeakingLogsResponse.java
> +	@Schema(enumAsRef = true, description = "스피킹 로그 조회 타입, NOT NULL")
오호 좋은데요!  
오늘 PR 리뷰 피드백 주시느라 고생 많으셨습니다!!!

2023-01-20 02:12 UTC, merged

2023-01-20 02:13 UTC, leeys1218 commented on be/src/main/java/com/example/be/core/application/dto/response/SpeakingLogsResponse.java
> +	@Schema(enumAsRef = true, description = "스피킹 로그 조회 타입, NOT NULL")
계속적인 피드백 감사드립니다.
오늘 말씀해주신 것들 기억해서 더 꼼꼼히 확인하고 작성할게요!

2023-01-20 02:14 UTC, nathan29849 commented on be/src/main/java/com/example/be/core/application/dto/response/SpeakingLogsResponse.java
> +	@Schema(enumAsRef = true, description = "스피킹 로그 조회 타입, NOT NULL")
좋습니다!
남은 프로젝트도 화이팅!!