Member 회원가입 기능 구현 및 테스트 작성
haru-speak/server pull request #40
Opened 2023-01-22 17:27 UTC by jakalroni

### ❗️ 이슈 번호

Closes #19 

<br><br>

### 📝 구현 내용

- Member 회원가입 관련 서비스 로직 작성
- 관련 Repository, Service, Controller, dto(MemberResponse) 작성
- 회원가입에 대한 MemberService 테스트(정상case, 중복회원case)

<img width="764" alt="image" src="https://user-images.githubusercontent.com/79403892/213929294-5c2e6721-935e-4245-a908-6219bc4ef830.png">

- 회원가입에 대한 MemberController 테스트(정상case)
    - MemberController 테스트의 경우, InitSpeakingLogControllerTest를 참고하여 InitMemberControllerTest를 작성!

<img width="764" alt="image" src="https://user-images.githubusercontent.com/79403892/213929465-2f641c0f-334d-4b65-bbb3-3ef8dc244917.png">

<br><br>

### 🙇🏻‍♂️ 리뷰어에게 부탁합니다!

- Controller 작성을 그동안 웹에서 하던 것처럼 html파일명을 return하거나 리다이렉트하거나... model.addAttribute()하는 방법만 알고 있었어서 이번에 작성한 Controller에 잘못된 부분이 있을 수도 있을 거라고 생각합니다...! 테스트코드는 SpeakingLog의 다른 테스트 코드 참고해서 작성했으니 잘못된 부분 발견 시 알려주시면 감사드리겠습니다!

아래는 Swagger UI에서 api로 등록된 모습입니다.

<img width="1344" alt="image" src="https://user-images.githubusercontent.com/79403892/213929182-2c0553eb-5fdb-4ce2-900e-5176a6f51103.png">

<img width="1344" alt="image" src="https://user-images.githubusercontent.com/79403892/213929267-52bca3da-9c94-4479-8c71-78e9ac9a8884.png">

<br><br>

2023-01-22 17:32 UTC, jakalroni commented on be/src/main/java/com/example/be/core/application/MemberService.java
> +  }
MemberService의 회원가입 메소드인 join()의 경우(saveMember에서 join으로 메소드명 변경했습니다), 

이메일을 통한 중복회원 검사 후, Repository에 save하도록 하였습니다.

2023-01-22 17:37 UTC, jakalroni commented on be/src/main/java/com/example/be/core/domain/member/Member.java
> +	}
MemberFormRequest로 입력받아 전달된 회원정보를 바탕으로 Member를 반환하는 정적 팩토리 메소드입니다.

(비밀번호의 경우, 보안을 위해 passwordEncoder를 거쳐 암호화 후 저장됩니다.)

2023-01-22 17:47 UTC, jakalroni commented on be/src/main/java/com/example/be/core/application/MemberService.java
> +  }
MemberController의 POST "/join"에 대한 BaseResponse의 제네릭으로 주입받기 위한 MemberResponse입니다.

먼저 Member.of()를 통해 MemberFormRequest를 바탕으로 password 암호화를 거친 member를 생성 후, MemberService의 join()을 통해 중복회원 예외 체크 후 Repository로 save()하도록 하였습니다.

`return null;`이 맞는지, 잘못된 부분이 있다면 어느 부분인지 알려주시면 감사드리겠습니다!

2023-01-22 17:49 UTC, jakalroni commented on be/src/main/java/com/example/be/core/web/MemberController.java
> +    MemberResponse response = memberService.create(memberFormRequest);
이런 식으로 Controller 작성하는 것이 맞는지 체크해주시면 감사드리겠습니다!

2023-01-22 17:49 UTC, jakalroni commented on be/src/main/java/com/example/be/core/web/MemberController.java
> +    return new BaseResponse<>(JOIN_SUCCESS, response);
이런 식으로 Controller 작성하는 것이 맞는지 체크해주시면 감사드리겠습니다!

2023-01-24 05:40 UTC, nathan29849 requested changes

2023-01-24 09:39 UTC, jakalroni commented on be/src/main/java/com/example/be/core/application/MemberService.java
> +//    }
이 부분 외에도 주석 처리한 부분들은 마지막에 PR이 merge될 준비가 됐을 때, 일괄로 정리해서 깔끔한 코드로 커밋하고 merge될 수 있도록 하겠습니다

2023-01-24 09:44 UTC, jakalroni commented on be/src/main/java/com/example/be/core/application/MemberService.java
> +  }
생각해보니 굳이 Response를 반환하는 부분과 Repository에 저장하는 부분을 구분해서 둘 필요가 없어보이네요...
해당 부분은 join 로직을 create 안에 포함시킨 후, new MemberResponse()로 반환하도록 수정하겠습니다!

2023-01-24 09:44 UTC, jakalroni commented on be/src/main/java/com/example/be/core/web/MemberController.java
> +    return new BaseResponse<>(JOIN_SUCCESS, response);
넵 해당 부분 반영하여 수정하겠습니다!

2023-01-24 09:44 UTC, jakalroni commented on be/src/main/java/com/example/be/core/application/MemberService.java
> +    }
Optional<Member> 타입으로 반환되는 걸 깜빡했네요... 이 내용 참고해서 람다식으로 중복회원 예외 확인하는 부분 수정해보겠습니다!

2023-01-24 09:45 UTC, jakalroni commented on be/src/main/java/com/example/be/core/application/dto/request/MemberFormRequest.java
> +  }
해당 부분은 MemberFormRequest(DTO)에서 생성자 안에서 바로 인코딩될 수 있게 수정하여 보안상으로 더 나을 수 있게 수정하겠습니다!

2023-01-26 13:33 UTC, nathan29849 approved these changes

2023-01-26 13:33 UTC, merged