Common/#43/study controller
haru-speak/server pull request #48
Opened 2023-01-25 06:23 UTC by leeys1218

### ❗️ 이슈 번호

Closes #43

- 스터디 관련 응답 코드 작성
- 임시 서비스 클래스 추가
- CRUD 컨트롤러 작성
- 목업 API 작성

### 🙇🏻‍♂️ 리뷰어에게 부탁합니다!

아직 검색과 좋아요, 찜, 댓글 기능에 대한 컨트롤러는 작성하지 않았습니다. 

피그마 화면, erd, api 명세서를 보시고 각 기능과 컨트롤러, DTO가 일치하는지 확인해주시면 감사하겠습니다!! 

### 💡 참고 자료

- 피그마(https://www.figma.com/file/FPIahJATLiZudwTdJnnGBO/%ED%95%98%EB%A3%A8%EC%8A%A4%ED%94%BD-(Team)?node-id=0%3A1)
- erd (https://www.erdcloud.com/d/MKSD3XnMafMQHPxk9)
- API 노션 (https://www.notion.so/API-c6195e5c6b2c44cfa9952f394182b8ff)

2023-01-25 06:37 UTC, nathan29849 requested changes
너무너무 고생 많으셨습니다
이틀도 안되는 시간에 이렇게 많이 해주실 줄 몰랐어요!
PR 관련 리뷰들은 코멘트에 남겨 놓았습니다!

2023-01-25 06:37 UTC, nathan29849 commented on be/src/main/java/com/example/be/common/response/ResponseCodeAndMessages.java
> +	DELETE_STUDY_SUCCESS("S-S005", "스터디 삭제를 성공했습니다."),
깔끔하네요! 👍

2023-01-25 06:37 UTC, nathan29849 commented on be/src/main/java/com/example/be/core/application/StudyService.java
> +public class StudyService {
`@Transactional(readOnly = true)`를 미리 붙여주면 좋을 것 같습니다!

2023-01-25 06:37 UTC, nathan29849 commented on be/src/main/java/com/example/be/core/application/StudyService.java
> +public class StudyService {
이와 관련해서 아래 메서드에서도 Read 관련 메서드가 아니면
메서드 위에 `@Transactional`를 미리 붙여주면 좋을 것 같습니다!

2023-01-25 06:37 UTC, nathan29849 commented on be/src/main/java/com/example/be/core/application/dto/request/StudyRequest.java
> +  private String timePerWeek;
주 횟수가 String보다는 Integer가 어울릴 것 같은데 연의 생각은 어떠신가요??

2023-01-25 06:37 UTC, nathan29849 commented on be/src/main/java/com/example/be/core/application/dto/request/StudyRequest.java
> +  private Integer level;
이 부분은 제가 추후 수정할 예정인데 Enum 타입으로 관리하면 어떨까 합니다! 
지금 수정하자는 말은 아닙니다!

2023-01-25 06:37 UTC, nathan29849 commented on be/src/main/java/com/example/be/core/application/dto/request/StudyRequest.java
> +  private String capacity;
인원과 관련되어 있기 때문에 String보다는 Integer가 더 낫지 않을까요??

2023-01-25 06:37 UTC, nathan29849 commented on be/src/main/java/com/example/be/core/application/dto/request/StudyRequest.java
> +  private String posterImg;
현재 멤버의 프로필 이미지도 profileImage라고 풀네임을 쓰고 있으니
줄임말보다 posterImage라고 변수명을 정하는 것은 어떨까요?

2023-01-25 06:37 UTC, nathan29849 commented on be/src/main/java/com/example/be/core/application/dto/response/StudiesResponse.java
> +public class StudiesResponse {
롬복으로 기본생성자를 protected 타입으로 넣어주시면 좋을 것 같습니다!!

2023-01-25 06:37 UTC, nathan29849 commented on be/src/main/java/com/example/be/core/application/dto/response/StudyDetailResponse.java
> +public class StudyDetailResponse {
마찬가지로 롬복으로 기본생성자를 protected 타입으로 넣어주시면 좋을 것 같습니다!!

2023-01-25 06:37 UTC, nathan29849 commented on be/src/main/java/com/example/be/core/application/dto/response/StudyResponse.java
> +public class StudyResponse {
마찬가지입니다!

2023-01-25 06:37 UTC, nathan29849 commented on be/src/main/java/com/example/be/core/domain/study/StudyType.java
> +        .orElseThrow(InvalidSpeakingLogTypeException::new);
StudyType인데, SpeakingLogType 에러를 던지는 것은 어울리지 않아보입니다!
따로 Exception을 만들어야 할 것 같아요

만약 Exception 만드는 방법이 조금 미숙하다면, 이전에 Exception들이 어떻게 만들어졌는지 확인해보시면 될 것 같아요!

2023-01-25 06:37 UTC, nathan29849 commented on be/src/main/java/com/example/be/core/web/StudyController.java
> +  public BaseResponse<StudiesResponse> find(StudyType type) {
이 메서드만 메서드 파라미터 내의 final 키워드가 빠져있네요??
혹시 이유가 있을까요?

2023-01-25 11:57 UTC, leeys1218 commented on be/src/main/java/com/example/be/core/application/StudyService.java
> +public class StudyService {
넵 구현 시 붙인다고 생각했는데 명세가 되어 있으니 그냥 붙여도 되겠네요!

2023-01-25 12:08 UTC, leeys1218 commented
빠른 피드백 감사드립니다!!

말씀하신 부분들을 assignment 관련 PR 에서도 점검하여 다시 커밋하겠습니다!

2023-01-26 08:25 UTC, nathan29849 commented on be/src/main/java/com/example/be/common/exception/study/InvalidStudyTypeException.java
> +package com.example.be.common.exception.study;
패키지 분리 좋았습니다!

2023-01-26 08:28 UTC, nathan29849 commented on be/src/main/java/com/example/be/core/application/dto/response/StudyResponse.java
> +  private Long studyId;
서비스 계층에서 Response DTO를 만들어줄 때 검증 단계를 거치면
Response에는 Bean Validation(ex. @NotNull)을 적용하지 않아도 될 것 같습니다.

@Schema는 Swagger 설정이니까 놔둬도 될 것 같아요
Study 관련 Response DTO에서 @NotNull과 같은 불필요한 어노테이션을 모두 지워주시면 좋을 것 같아요!

2023-01-26 08:30 UTC, nathan29849 commented on be/src/main/java/com/example/be/core/application/dto/response/StudyDetailResponse.java
> +public class StudyDetailResponse {
앗 제가 잘못 알려드렸네요.. Response DTO에서는 모든 필드를 final로 하니까, 기본 생성자는 굳이 만들지 않아도 될 것 같아요 ㅠㅠ
이미 잘 해 놓으셨는데, 번거롭게 해드려 죄송합니다 ㅠㅠ

다시 변경 부탁드릴게요..!!

2023-01-26 08:51 UTC, HanKwanJin commented
연 고생 많으셨습니다!

2023-01-26 08:54 UTC, leeys1218 commented on be/src/main/java/com/example/be/core/application/dto/response/StudyDetailResponse.java
> +public class StudyDetailResponse {
앗 아닙니다 제가 피드백 적용 전에 Reponse 값들 변하는지 한번 더 생각해 봤으면 됐었는데,,


assignment 관련 response도 다시 수정 후 커밋하고 디엠으로 머지 요청 드릴게요!

2023-01-26 08:54 UTC, leeys1218 commented on be/src/main/java/com/example/be/core/application/dto/response/StudyResponse.java
> +  private Long studyId;
네 확인했습니다!

2023-01-26 11:59 UTC, nathan29849 approved these changes
너무 고생많으셨습니다!!

2023-01-26 11:59 UTC, merged