AWS S3 설정 및 파일 업로드 기능 구현과 테스트 코드 작성
haru-speak/server pull request #56
Opened 2023-01-26 15:05 UTC by HanKwanJin

### ❗️ 이슈 번호

Closes #42 

<br><br>

### 📝 구현 내용

- AWS S3 Bucket 만들기
- 파일 업로드를 위한 AWS S3 설정
- S3Mock을 이용한 파일 업로드 테스트 코드 작성

**이미지 업로드**

[POST] `https://api.haru-speak.site/upload/image`

```json
{
    "code": "S-F001",
    "message": "이미지 파일 업로드의 성공했습니다.",
    "data": {
        "fileUrl": "이미지 url",
        "filePath": "image/이미지_이름.jpeg"
    }
}
```
![image](https://user-images.githubusercontent.com/49313910/214870189-35dc0aa4-50db-42b1-a093-9f9d933b9eca.png)

**음성 파일 업로드**

[POST] `https://api.haru-speak.site/upload/voice`

```json
{
    "code": "S-F002",
    "message": "음성 파일 업로드의 성공했습니다.",
    "data": {
        "fileUrl": 음성 파일 url,
        "filePath": "voice/음성_파일_이름.mid"
    }
}
```
![image](https://user-images.githubusercontent.com/49313910/214870253-1935a9b8-f187-4fff-a9dd-c0e309183794.png)
---
**테스트**
![image](https://user-images.githubusercontent.com/49313910/214870302-581d71da-2aad-4d01-b8d0-4e6ffab108f4.png)

### 💡 참고 자료

- [Spring에서 S3로 파일업로드 및 테스트 하는 방법](https://europani.github.io/aws/2022/03/03/004-spring-s3.html#h-%ED%85%8C%EC%8A%A4%ED%8A%B8)

2023-01-26 15:21 UTC, nathan29849 requested changes
S3 테스트는 쉽지 않았을텐데 고생많으셨습니다!
리뷰 관련해서 아래 코멘트로 남겨 놓았으니 확인 부탁드릴게요~

2023-01-26 15:21 UTC, nathan29849 commented on be/src/main/java/com/example/be/core/application/dto/response/FileUploadResponse.java
> +    @NotBlank
Response DTO 관련 팀 규칙을 참고해서 수정해주세요!

2023-01-26 15:21 UTC, nathan29849 commented on be/src/main/java/com/example/be/core/application/FileUploadService.java
> +        return category + "/" + fileName + fileExtension;
카테고리별로 파일 이름을 정하는건 정말 좋은 것 같습니다!

2023-01-26 15:22 UTC, HanKwanJin commented on be/src/main/java/com/example/be/common/response/ResponseCodeAndMessages.java
> +	VOICE_UPLOAD_SUCCESS("S-F002", "음성 파일 업로드의 성공했습니다."),
이 부분 Conflicts이 발생했네요! main에 추가됐던 부분 때문인 것 같습니다! 다른 분들도 다 확인하시면 같이 수정해서 병합해요 😃

2023-01-26 15:25 UTC, HanKwanJin commented on be/src/main/java/com/example/be/core/application/QuestionService.java
> +@Transactional(readOnly = true)
저희 어노테이션 규칙에 따라서 길이가 긴 것을 아래로 내렸습니다!

2023-01-26 15:26 UTC, HanKwanJin commented on be/src/main/java/com/example/be/core/application/dto/response/FileUploadResponse.java
> +    @NotBlank
넵! 이 부분 수정해서 커밋하겠습니다!

2023-01-26 15:35 UTC, HanKwanJin commented on be/src/main/java/com/example/be/core/application/FileUploadService.java
> +        return category + "/" + fileName + fileExtension;
나단이 좋은 키워드를 던져주셔서 방금 몇 곳의 블로그를 찾아봤는데요! 저는 좋은 것 같습니다. 현재 버킷이 퍼블릭으로 열려있는데 이 부분을 설정할 때 혹시 보안 적으로 문제가 되진 않을까 걱정이 됐었거든요. pre-signed url 방식을 사용하면 사용자에게 임시 접근 권한을 부여하니까 나단이 말한 장점들 + 보안면으로도 장점이 될 것 같네요.

다른 분들도 읽어보면 좋을 것 같아서 아래 참고한 블로그 링크를 남겨두겠습니다!

**참고자료**
- [📚 S3 Pre-signed URL 공유하기](https://inpa.tistory.com/entry/AWS-%F0%9F%93%9A-S3-Pre-signed-URL-%EA%B3%B5%EC%9C%A0%ED%95%98%EA%B8%B0)

2023-01-26 15:37 UTC, nathan29849 commented on be/src/main/java/com/example/be/common/config/AwsS3Config.java
> +    private String region;
정말 중요한 부분을 잘 짚으신 것 같아요! 
저도 무심코 @Value만 쓰고 있었는데 좋은 인사이트를 얻었네요
일정이 허락하지 않으면, 당장은 리팩토링하기 쉽지 않겠지만, 추후에 꼭 리팩토링 해보면 좋을 것 같습니다

저도 알아본 관련 자료들을 공유 드릴게요!
- https://velog.io/@cmsskkk/SpringBoot-ConfigurationProperties
- https://github.com/jjik-muk/sikdorak/blob/dev/be/src/main/java/com/jjikmuk/sikdorak/common/properties/AwsProperties.java

2023-01-26 15:44 UTC, nathan29849 commented on be/src/main/java/com/example/be/core/application/FileUploadService.java
> +        return category + "/" + fileName + fileExtension;
도전해보면 좋을 것 같아요!
동동이 여유가 되면 당장 해도 좋고, 아니라면 추후에 리팩토링을 하셔도 좋을 것 같네요

2023-01-26 15:46 UTC, nathan29849 commented on be/src/main/java/com/example/be/core/application/QuestionService.java
> +@Transactional(readOnly = true)
아 그랬군요! 너무 좋습니다!!

2023-01-26 15:49 UTC, HanKwanJin commented on be/src/main/java/com/example/be/core/application/FileUploadService.java
> +        return category + "/" + fileName + fileExtension;
12시가 지나서 오늘이라고 하겠습니다! 오늘 오후 해가 떨어지기 전까지는 한번 적용해보도록 도전해보겠습니다! 급한 다른 부분들도 있으니까 해보고 너무 오래 걸리겠다 싶으면 말씀드릴게요!

2023-01-27 06:29 UTC, HanKwanJin commented on be/src/main/java/com/example/be/core/application/FileUploadService.java
> +    }
![S3 Pre-signed URL 공유하기](https://user-images.githubusercontent.com/49313910/215023090-f6729a9b-c22b-4100-bb74-38b30c356c60.png)
[사진 출처] : [S3 Pre-signed URL 공유하기](https://inpa.tistory.com/entry/AWS-%F0%9F%93%9A-S3-Pre-signed-URL-%EA%B3%B5%EC%9C%A0%ED%95%98%EA%B8%B0)

서버에서 파일을 직접 S3에 업로드 방식을 버리고 Pre-signed URL 방식을 통해 서버는 임시 권한을 부여하는 URL만 제공하고 프론트에서 파일을 업로드 하도록 변경하였습니다.  

Pre-signed URL 방식을 사용할 때 이점을 다음과 같습니다.

- 스프링 서버의 과부하(파일을 받고 S3에 업로드 하는 과정)를 피할 수 있다. (feat. 나단)
- 미리 지정해 둔 타입과 파일 크기로 파일에 대한 검증 처리를 AWS S3에 맡길 수 있다. (feat. 나단)
- S3 버킷을 인증된 URL을 가진 이용자만 접근 가능하도록 해서 기존 방식보다 보안 적으로 좋다. (feat. 동동)

2023-01-27 06:34 UTC, HanKwanJin commented on be/src/main/java/com/example/be/core/application/FileUploadService.java
> +        return category + "/" + fileName + fileExtension;
@jakalroni @leeys1218  @nathan29849 Pre-signed URL 적용해봤습니다! 확인 부탁드려요 :)

2023-01-27 06:36 UTC, HanKwanJin commented on be/src/main/java/com/example/be/core/application/FileUploadService.java
> +    }
지금 보니 업로드 할 수 있는 권한 부여 시간을 하루로 줄 필요가 없어보이네요! ... 네트워크 상황도 고려해서 10분 정도로 설정하면 괜찮을까요? 다른 분들의 생각이 궁금합니다!

2023-01-27 12:55 UTC, nathan29849 commented on be/src/main/java/com/example/be/core/web/FileUploadController.java
> +            GENERATE_IMAGE_UPLOAD_RUL_SUCCESS,
오타가 있는 것 같네요! 확인 부탁드립니다~

2023-01-27 12:58 UTC, nathan29849 commented on be/src/main/java/com/example/be/core/application/FileUploadService.java
> +    public String generateUrl(String fileName, HttpMethod httpMethod) {
generateUrl은 현재 클래스 외부에서 쓰이지 않는 것 같은데 public으로 지정해 둔 이유가 있을까요?

2023-01-27 12:59 UTC, nathan29849 commented on be/src/main/java/com/example/be/core/application/FileUploadService.java
> +    }
그림 첨부 매우 좋습니다! 10분정도로 줄여도 좋을 것 같아요!

2023-01-27 14:07 UTC, HanKwanJin commented on be/src/main/java/com/example/be/core/application/FileUploadService.java
> +    }
넵 바꿔서 커밋해두겠습니다 :)

2023-01-27 14:08 UTC, HanKwanJin commented on be/src/main/java/com/example/be/core/web/FileUploadController.java
> +@RequestMapping(value = "/files")
넵! file 로 바꿔놓겠습니다!

2023-01-27 14:09 UTC, HanKwanJin commented on be/src/main/java/com/example/be/core/web/FileUploadController.java
> +            GENERATE_IMAGE_UPLOAD_RUL_SUCCESS,
아차차차ㅏ 감사합니다 오타 발견..! 바꿔두겠습니다.

2023-01-27 14:14 UTC, HanKwanJin commented on be/src/main/java/com/example/be/core/application/FileUploadService.java
> +    public String generateUrl(String fileName, HttpMethod httpMethod) {
아 그렇네요! 꼼꼼히 고려하지 못 했습니다.. 현재 클래스에서만 쓰이고 있으니까 public 으로 안해야겠네요!! private로 변경하겠습니다 :)

2023-01-27 14:18 UTC, nathan29849 requested changes

2023-01-27 14:18 UTC, nathan29849 commented on be/src/main/java/com/example/be/core/application/FileUploadService.java
> +    @Async
붙이신 이유가 궁금합니다!

2023-01-27 16:58 UTC, nathan29849 requested changes

2023-01-27 16:58 UTC, nathan29849 commented on be/build.gradle
> +    implementation "org.springframework.cloud:spring-cloud-starter-aws:2.2.6.RELEASE"
`spring-cloud-starter-aws:2.2.6.RELEASE`의 보안상 취약점 때문에 
[io.awspring.cloud:spring-cloud-starter-aws](https://mvnrepository.com/artifact/io.awspring.cloud/spring-cloud-starter-aws)를 써야 한다고 해요!
아래 블로그 첨부해둘테니 확인 부탁드릴게요!
- https://www.kua.kr/183

2023-01-28 04:51 UTC, HanKwanJin commented on be/src/main/java/com/example/be/core/application/FileUploadService.java
> +    @Async
pre-signed url 방식을 구현 할 때 참고한 글에서 `@Async` 어노테이션을 붙여준 걸 보고 '아 비동기 방식을 이용하면 성능이 더 좋아지나보다!' 하고 따라 적고 넘어갔네요..😢  `@Async` 에 대해서 좀 더 찾아보니 저는 `@Async` 를 잘못 사용하고 있었습니다. `@Async`를 사용하려면 설정 클래스에 `@EnableAsync` 과 쓰레드 풀을 따로 설정해주어야 하더군요.

고민을 해본 결과 제 생각에는 지금 `@Async` 어노테이션을 사용하지않고 앱이 어느정도 완성되고 테스트 하는 단계에서 프론트분들이 s3 pre-signed url 을 받는 과정이 성능이 잘 안나온다면 그때 비동기 처리에 대해서 고민하는게 맞는 것 같습니다.

나단의 생각은 어떤가요??

2023-01-28 04:51 UTC, nathan29849 commented on be/src/main/java/com/example/be/core/application/FileUploadService.java
> +    @Async
네 저도 추후에 사용해보면 될 것 같다는 생각에 동의합니다!

2023-01-28 04:53 UTC, HanKwanJin commented on be/build.gradle
> +    implementation "org.springframework.cloud:spring-cloud-starter-aws:2.2.6.RELEASE"
와우 이런 부분까지! 코드도 바뀌는 부분없이 그대로 유지된다는 점도 좋네요! 변경해서 커밋해두겠습니다

2023-01-28 05:38 UTC, nathan29849 approved these changes
고생많으셨습니다!

2023-01-28 05:38 UTC, merged