Study, Assignment 관련 Entity 작성
haru-speak/server pull request #60
Opened 2023-01-27 14:03 UTC by HanKwanJin

### ❗️ 이슈 번호

Closes #59 

<br>

### 📝 구현 내용

- Assignment Entity 작성
    - AssignmentMember Entity 작성
- Study Entity 작성
    - StudyComment Entity 작성
    - StudyFavorite Entity 작성
    - StudyInterest Entity 작성
    - StudyMember Entity 작성

2023-01-27 14:31 UTC, leeys1218 commented on be/src/main/java/com/example/be/core/domain/assignment/AssignmentMember.java
> +package com.example.be.core.domain.assignment;
다대다 관계에서 단방향 매핑을 위해 추가한 entity 클래스는 관련 서비스가 구현되는 entity가 있는 패키지에 두었습니다.

member 서비스에서 assignment를 조회 x
assignment 서비스에서 member를 조회 o

2023-01-27 14:31 UTC, leeys1218 commented on be/src/main/java/com/example/be/core/domain/study/StudyInterest.java
> +package com.example.be.core.domain.study;
멤버 - 스터디, 멤버 - 찜도 마찬가지로 스터디에서 멤버를 조회하여 서비스를 구현하기 때문에 스터디 패키지에 Entity 클래스를 두었습니다. 

study와 member의 다대다 관계를 표현하는 Entity들을 따로 다른 패키지로 관리하는 것도 방법도 있을 것 같습니다!

2023-01-27 14:37 UTC, nathan29849 commented on be/src/main/java/com/example/be/core/domain/assignment/AssignmentMember.java
> +package com.example.be.core.domain.assignment;
너무 좋습니다!

2023-01-27 14:43 UTC, nathan29849 requested changes
도메인 엔티티 작성하시느라 고생 많으셨습니다!!

관련 리뷰는 코멘트로 달아두었으니 확인 부탁드려요~

2023-01-27 14:43 UTC, nathan29849 commented on be/src/main/java/com/example/be/core/domain/assignment/Assignment.java
> +public class Assignment {
과제도 사용자가 실수로 지웠다가 다시 복구할 수도 있을 것 같아요
그래서 soft delete 방식을 사용하도록 바꾸면 어떨까요??

2023-01-27 14:43 UTC, nathan29849 commented on be/src/main/java/com/example/be/core/domain/study/StudyComment.java
> +public class StudyComment extends BaseEntity {
Comment에 생성 또는 수정에 대한 시간 기록이 필요할 수도 있으니 BaseEntity를 상속하신게 맞나요?

2023-01-27 14:43 UTC, nathan29849 commented on be/src/main/java/com/example/be/core/domain/study/StudyInterest.java
> +package com.example.be.core.domain.study;
추후 기능구현까지 완료하고 패키지 구조를 개선해 보는 리팩토링을 진행해보면 좋을 것 같네요!

2023-01-27 14:49 UTC, leeys1218 commented on be/src/main/java/com/example/be/core/domain/assignment/Assignment.java
> +public class Assignment {
충분히 그럴 수도 있겠네요!
마침 과제 생성일과 제출 기한을 이용하여 남은 시간을 계산할 경우 등  BaseEntity를 상속 받는 것에 대해서도 고민했었습니다.

그럼 BaseEntity를 상속받아서 진행해야 할까요??

2023-01-27 15:54 UTC, nathan29849 commented on be/src/main/java/com/example/be/core/domain/assignment/Assignment.java
> +public class Assignment {
네 그러면 좋을 것 같습니다!

2023-01-28 11:09 UTC, nathan29849 approved these changes

2023-01-28 11:09 UTC, leeys1218 approved these changes

2023-01-28 11:09 UTC, merged